chore: merge next into main for production release (#148)
Co-authored-by: TWIN GitHub Bot <github@twindev.org>

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -3,6 +3,17 @@ name: Build
 on:
   workflow_dispatch:
   pull_request:
+    branches:
+      - next
+    paths-ignore:
+      - '**/*.md'
+      - '.github/**'
+  push:
+    branches:
+      - next
+    paths-ignore:
+      - '**/*.md'
+      - '.github/**'
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
@@ -10,83 +21,58 @@ concurrency:
 
 jobs:
   dist-all-packages:
-    runs-on: ubuntu-latest
-
-    # Add env vars for tests
-    env:
-      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
-      TEST_2_MNEMONIC: ${{ secrets.TEST_2_MNEMONIC }}
-      TEST_NODE_MNEMONIC: ${{ secrets.TEST_NODE_MNEMONIC }}
+    # No need to trigger on merging pull request 'chore: release next'
+    # or 'docs: regenerate package documentation' as they have already performed a build
+    if: "${{ github.event_name != 'push' || (!startsWith(github.event.head_commit.message, 'Merge pull request') && !startsWith(github.event.head_commit.message, 'chore: release next') && !startsWith(github.event.head_commit.message, 'docs: regenerate package documentation') && !startsWith(github.event.head_commit.message, 'chore: merge next into main for production release')) }}"
+    runs-on:
+      labels: ${{ github.event.repository.private && 'self-hosted' || 'ubuntu-latest' }}
+      group: ${{ github.event.repository.private && 'twin' || 'default' }}
 
     steps:
-      # Get the code
+      # Clone the repository to the runner
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
+
+      # Load test environment variables into the runner environment
+      - name: Load Test Environment Variables
+        shell: bash
+        run: |
+          printf '%s\n' "${{ secrets.TWIN_TEST_ENV_VARS }}" >> "$GITHUB_ENV"
 
       # Setup Node
       - name: Setup Node
-        uses: actions/setup-node@v4
+        uses: actions/setup-node@v6
         with:
-          node-version: 20
+          node-version: 24
 
-      # Install dependencies
+      # Install dependencies with retry
       - name: Install dependencies
-        run: npm ci
-
-      # Setup any services required for tests here
-      # Start PostgreSQL service only for PostgreSQL package
-      - name: Start PostgreSQL Service
-        run: docker run -d --name twin-entity-storage-postgresql -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -p 5432:5432 postgres:latest
-
-        # Start ScyllaDB service only for ScyllaDB package
-      - name: Start ScyllaDB Service
-        run: docker run -d --name twin-entity-storage-scylladb -p 9042:9042 scylladb/scylla:5.4.9
-
-        # Start DynamoDB service only for DynamoDB package
-      - name: Start DynamoDB Service
-        run: docker run -d --name twin-entity-storage-dynamodb -p 8000:8000 amazon/dynamodb-local:latest
-
-        # Start MySQL service only for MySQL package
-      - name: Start MySQL Service
-        run: docker run -d --name twin-entity-storage-mysql -e MYSQL_ROOT_PASSWORD=password -p 3306:3306 mysql:latest
-
-        # Start MongoDB service only for MongoDB package
-      - name: Start MongoDB Service
-        run: docker run -d --name twin-entity-storage-mongo -p 27017:27017 mongo:latest
-
-        # Start Firestore service only for Firestore package
-      - name: Start Firestore Emulator
-        run: docker run -d --name twin-entity-storage-firestore -p 8080:8080 gcr.io/google.com/cloudsdktool/cloud-sdk:emulators gcloud beta emulators firestore start --host-port=0.0.0.0:8080
-
-      - name: Increase aio-max-nr
-        # Increase the maximum number of asynchronous I/O (AIO) requests that can be queued to
-        # the kernel. This is necessary for the CosmosDB Emulator to function properly, as it
-        # requires a higher limit for I/O operations.
-        # Reference: https://man7.org/linux/man-pages/man5/proc.5.html#fs.aio-max-nr
-        run: echo 1048576 | sudo tee /proc/sys/fs/aio-max-nr
-
-        # Start CosmosDB service only for CosmosDB package
-      - name: Pull CosmosDB Emulator Docker Image
-        run: docker pull mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
-
-      - name: Run CosmosDB Emulator
-        run: docker run --publish 8081:8081 --publish 10250-10255:10250-10255 --name twin-entity-storage-cosmos --detach --platform=linux/amd64 --memory=3g --cpus=2.0 mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
-
-      - name: Wait for CosmosDB Emulator to be Ready
         run: |
-          for i in {1..30}; do
-            if nc -zv localhost 8081; then
-              echo "CosmosDB emulator is ready!"
-              break
-            fi
-            echo "Waiting for CosmosDB emulator to be ready..."
-            sleep 5
+          for i in {1..5}; do
+            npm ci && break || {
+              if [ $i -eq 5 ]; then
+                echo "npm ci failed after 3 attempts"
+                exit 1
+              fi
+              echo "npm ci failed, retrying in 30 seconds (attempt $i/3)..."
+              sleep 30
+            }
           done
 
-      # End setup for tests
+      # Setup any services required for tests here
+      - name: Setup Test Environment
+        uses: ./.github/workflows/setup-test-env
+        with:
+          test_env_vars: ${{ secrets.TWIN_TEST_ENV_VARS }}
 
       # Run Lint and Dist
       - name: Run Lint and Dist
         run: |
           npm run lint
           npm run dist
+          npm run docs
+
+      # Always teardown the environment, necessary to cleanup self-hosted
+      - name: Teardown Test Environment
+        if: always()
+        uses: ./.github/workflows/teardown-test-env
